# Defines commands used by rocm-smi and perf
# Defines env variables required by ld
# Do not remove `-j` flag from perf's base command
# Do not remove `--json` flag from rocm-smi's base command
#
# Warning:
#  - bpftrace requires sudo
#  - open `sudo visudo`
#  - append `your_username ALL=(ALL) NOPASSWD: /usr/local/bin/bpftrace`

commands:
  rocm_smi:
    base_command:
      - "rocm-smi"
      - "--showuse"
      - "--showmemuse"
      - "--json"
    device_flag: "--device="
    device_index: 0

  perf:
    base_command:
      - "perf"
      - "stat"
      - "-j"
      - "-e"

  bash_command_wrapper:
    base_command:
      - "sh"
      - "-c"
      - 'kill -STOP $$; exec "$@"'
      - "--"

  bpftrace_startup:
    base_command:
      - "sudo"
      - "bpftrace"
      - "-q"
    pid_flag: "-p"
    script: "scripts/linker_prof.bt"